import Logo from '../components/logo/logo'
import { logoValues } from "../components/logo/logo.config"
import { MemberCard } from '../components/card/card'
import { membersValues } from "../components/card/card.config"
import Roadmap from '../components/roadmap/roadmap'
import { roadmapValues } from "../components/roadmap/roadmap.config"

const AboutUs = () => {
  return (
    <>
      <Logo values={logoValues}/>

      <div className={'flex flex-wrap gap-12 justify-center my-16'}>
        {membersValues.map((card, index) => {
          return <MemberCard key={`nft_${index}`} values={card}/>
        })}
      </div>
      
      <Roadmap values={roadmapValues}/>
    </>
  );
}

AboutUs.title = 'About Us';
AboutUs.description = 'Generated by create next app';
AboutUs.header = '¡Conoce al equipo!';

export default AboutUs;