import Form from '../components/form/form'
import { contactValues } from "../components/form/form.config"

const Contact = () => {
  return <Form values={contactValues} name="contact" entries={7}/>
}

Contact.title = 'Contacto';
Contact.description = 'Generated by create next app';
Contact.header = 'Contacta con nosotros';

export default Contact;
