import Accordion from '../components/accordion/accordion'
import { FAQValues } from "../components/accordion/accordion.config"

const FAQ = () => {
  return <Accordion values={FAQValues}/>
}

FAQ.title = 'FAQ';
FAQ.description = 'Generated by create next app';
FAQ.header = '¿Tienes alguna duda? Bienvenido a nuestro FAQ';

export default FAQ;