import Jumbotron from '../components/jumbotron/jumbotron'
import { MemberCard } from '../components/card/card'
import { jumboLandingValues_1, jumboLandingValues_2, jumboLandingValues_3 } from "../components/jumbotron/jumbotron.config"
import { blockchainValues, economyValues } from "../components/card/card.config"

const LandingPage = () => {
	return (
		<div className="my-16 flex flex-wrap justify-center items-center gap-y-20">
			<Jumbotron values={jumboLandingValues_1}/>

			<h2 className="no-underline font-semibold text-4xl text-center text-stone-200 drop-shadow-[4px_4px_4px_#000000]">Exploremos las posibilidades de la tecnología blockchain</h2>
			<div className={'flex flex-wrap gap-12 justify-center mb-16'}>
        {blockchainValues.map((card, index) => {
          return <MemberCard key={`blockchain_${index}`} values={card}/>
        })}
      </div>

			<Jumbotron values={jumboLandingValues_2}/>

			<h2 className="no-underline font-semibold text-4xl text-center text-stone-200 drop-shadow-[4px_4px_4px_#000000]">Una comunidad con su propia economía</h2>
			<div className={'flex flex-wrap gap-12 justify-center mb-16'}>
        {economyValues.map((card, index) => {
          return <MemberCard key={`economy_${index}`} values={card}/>
        })}
      </div>

			<Jumbotron values={jumboLandingValues_3}/>
		</div>
	);
}

LandingPage.title = 'Inicio';
LandingPage.description = 'Generated by create next app';
LandingPage.header = 'Nebula Space Market';

export default LandingPage;
