import { ProductCard } from '../components/card/card'
import { nftsValues } from "../components/card/card.config"
import { useEffect, useState } from "react";

const NFTs = () => {
  const [nftsCards, setNftsCards] = useState([]);

  useEffect(() => {
    if(nftsValues){
      setNftsCards(
        nftsValues.map((card, index) => {
          return <ProductCard key={`nft_${index}`} values={card}/>
        })
      );
    }
  }, [nftsValues]);

  return (
    <div className={'flex flex-wrap gap-12 justify-center my-16'}>
      {nftsCards ? nftsCards : 'No rulo'}
    </div>
  );
}


NFTs.title = 'NFTs';
NFTs.description = 'Generated by create next app';
NFTs.header = 'Listado de NFTs';

export default NFTs;
