import Text from '../components/text/text'
import { privacyValues } from "../components/text/text.config"

const Privacy = () => {
  return <Text values={privacyValues}/>
}

Privacy.title = 'Privacidad';
Privacy.description = 'Generated by create next app';
Privacy.header = 'Política de Privacidad';

export default Privacy;
