import { WishlistItem } from '../components/wishlist/wishlist'
import { wishlistValues } from "../components/wishlist/wishlist.config"
import { useState } from "react";
import { useWishlistContext } from "../contexts/wishlist_context";

const Wishlist = () => {
  const { items } = useWishlistContext();

  return items.length ? (
    <div className={'flex flex-wrap gap-8 justify-center my-16'}>
      {items.map((item, index) => {
        return <WishlistItem key={`item_${index}`} values={item}/>
      })}
    </div>
  ) : (
    <div className={'flex justify-center items-center my-16'}>
      ¿Aún no has guardado ningún producto?¡Encuentra algo que te guste y guárdalo para más tarde!
    </div>
  );
}

Wishlist.title = 'Wishlist';
Wishlist.description = 'Generated by create next app';
Wishlist.header = 'Wishlist';

export default Wishlist;
